### PR TITLE
LockDrop optimization

### PR DESCRIPTION
**Pull request by lazovicff**
Changes include:

1) Deployment costs:
before - `~1006000`
now - `~936000`

2) `lock` function cost:
before: `~197000`
now: `~110000`

3) `unlock` and `withdraw` are pretty much the same as before, `26000` and `24000` respectively.

4) Storage variables removed:
`totalDeposits`, `totalEffectiveDeposits`, `initialValuation`, `beginning` and `participants` for the same reason:
Either they are not used anywhere in the smart contract, or the information can be derived from other variables.

5) Removed `effectiveAmount` and `receivingPubKey` from `Lock` struct for the same reason described above, but added `numOfTokens` (it is needed inside `unlock` later so it would be more efficient to save it in the storage)

6) I introduced `calculateEffectiveAmount` function which will calculate bonus given to the user based on lock duration:
from 6 months to 1 year: 3.75%
from 1 year to 1.5 years: 7.5%
from 1.5 years to 2 years: 11.25%
above 2 years: 15%

7) Calculating number of tokens bought: `effectiveAmount / tokenPrice`.

8) Making the unlocked tokens inside `unlock` function to be available to other participants.

9) Added `eth-gas-reporter`.

Few more things to mention:
From previous code review i saw that you were talking about discount mechanism instead of bonus-like mechanism implemented here. Let me know what do you prefer as these are 2 separate things e.g:
- bonus case:
  - Token price - `10 eth`
  - User locks `100 eth` for 2 years, with bonus `15%`, total is `115 eth`.
  - He will buy `11.5` (115 / 10) tokens

- discount case:
  - Token price - `10 eth`
  - User locks `100 eth` for 2 years, discount is `15%`, each token is `8.5 ether`.
  - He will buy `11.7` tokens

### CODE REVIEW

**Review by drewstone — CHANGES_REQUESTED** [review]
Looks great and thanks so much for these awesome updates!

@filiplazovic I have one question because I had also written a script to aggregate and format the participants of the lock drop once it had ended (for use in a genesis spec of Edgeware). Can you update the script [here](https://github.com/hicommonwealth/cw-hq/blob/master/scripts/lockdrop.js) to pull all participants of the lockdrop? I presume you would need to look at the events incident on the contract. Other than that I'm happy to merge this in.

**Comment by lazovicff** [comment]
@drewstone Sorry i didn't notice that file. Yes, i would need to get all the events to find all participants. I will do that inside this PR

**Comment by lazovicff** [comment]
@drewstone I updated the script, added truffle 5 and few minor things. It can be reviewed

**Review by drewstone — APPROVED** [review]
Awesome! Thanks for tidying things up @filiplazovic

**Pull request merged**
